// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: nyct-subway.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// NYCT Subway extensions for GTFS-realtime
// Based on the MTA's published nyct-subway.proto specification

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// NYCT Subway extensions for the feed header
public struct NyctFeedHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nyctSubwayVersion: String {
    get {_nyctSubwayVersion ?? String()}
    set {_nyctSubwayVersion = newValue}
  }
  /// Returns true if `nyctSubwayVersion` has been explicitly set.
  public var hasNyctSubwayVersion: Bool {self._nyctSubwayVersion != nil}
  /// Clears the value of `nyctSubwayVersion`. Subsequent reads from it will return its default value.
  public mutating func clearNyctSubwayVersion() {self._nyctSubwayVersion = nil}

  public var tripReplacementPeriod: [NyctTripReplacementPeriod] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TripReplacementPeriod_ReplacementPeriod: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case unknown = 0

    public init() {
      self = .unknown
    }

  }

  public init() {}

  fileprivate var _nyctSubwayVersion: String? = nil
}

public struct NyctTripReplacementPeriod: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var routeID: String {
    get {_routeID ?? String()}
    set {_routeID = newValue}
  }
  /// Returns true if `routeID` has been explicitly set.
  public var hasRouteID: Bool {self._routeID != nil}
  /// Clears the value of `routeID`. Subsequent reads from it will return its default value.
  public mutating func clearRouteID() {self._routeID = nil}

  public var replacementPeriod: TransitRealtime_TimeRange {
    get {_replacementPeriod ?? TransitRealtime_TimeRange()}
    set {_replacementPeriod = newValue}
  }
  /// Returns true if `replacementPeriod` has been explicitly set.
  public var hasReplacementPeriod: Bool {self._replacementPeriod != nil}
  /// Clears the value of `replacementPeriod`. Subsequent reads from it will return its default value.
  public mutating func clearReplacementPeriod() {self._replacementPeriod = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _routeID: String? = nil
  fileprivate var _replacementPeriod: TransitRealtime_TimeRange? = nil
}

/// NYCT Subway extensions for trip descriptors
public struct NyctTripDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var trainID: String {
    get {_trainID ?? String()}
    set {_trainID = newValue}
  }
  /// Returns true if `trainID` has been explicitly set.
  public var hasTrainID: Bool {self._trainID != nil}
  /// Clears the value of `trainID`. Subsequent reads from it will return its default value.
  public mutating func clearTrainID() {self._trainID = nil}

  public var isAssigned: Bool {
    get {_isAssigned ?? false}
    set {_isAssigned = newValue}
  }
  /// Returns true if `isAssigned` has been explicitly set.
  public var hasIsAssigned: Bool {self._isAssigned != nil}
  /// Clears the value of `isAssigned`. Subsequent reads from it will return its default value.
  public mutating func clearIsAssigned() {self._isAssigned = nil}

  public var direction: NyctTripDescriptor.Direction {
    get {_direction ?? .north}
    set {_direction = newValue}
  }
  /// Returns true if `direction` has been explicitly set.
  public var hasDirection: Bool {self._direction != nil}
  /// Clears the value of `direction`. Subsequent reads from it will return its default value.
  public mutating func clearDirection() {self._direction = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Direction: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case north = 1
    case east = 2
    case south = 3
    case west = 4

    public init() {
      self = .north
    }

  }

  public init() {}

  fileprivate var _trainID: String? = nil
  fileprivate var _isAssigned: Bool? = nil
  fileprivate var _direction: NyctTripDescriptor.Direction? = nil
}

/// NYCT Subway extensions for stop time updates
public struct NyctStopTimeUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scheduledTrack: String {
    get {_scheduledTrack ?? String()}
    set {_scheduledTrack = newValue}
  }
  /// Returns true if `scheduledTrack` has been explicitly set.
  public var hasScheduledTrack: Bool {self._scheduledTrack != nil}
  /// Clears the value of `scheduledTrack`. Subsequent reads from it will return its default value.
  public mutating func clearScheduledTrack() {self._scheduledTrack = nil}

  public var actualTrack: String {
    get {_actualTrack ?? String()}
    set {_actualTrack = newValue}
  }
  /// Returns true if `actualTrack` has been explicitly set.
  public var hasActualTrack: Bool {self._actualTrack != nil}
  /// Clears the value of `actualTrack`. Subsequent reads from it will return its default value.
  public mutating func clearActualTrack() {self._actualTrack = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _scheduledTrack: String? = nil
  fileprivate var _actualTrack: String? = nil
}

// MARK: - Extension support defined in nyct-subway.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension TransitRealtime_FeedHeader {

  public var nyctFeedHeader: NyctFeedHeader {
    get {return getExtensionValue(ext: Extensions_nyct_feed_header) ?? NyctFeedHeader()}
    set {setExtensionValue(ext: Extensions_nyct_feed_header, value: newValue)}
  }
  /// Returns true if extension `Extensions_nyct_feed_header`
  /// has been explicitly set.
  public var hasNyctFeedHeader: Bool {
    return hasExtensionValue(ext: Extensions_nyct_feed_header)
  }
  /// Clears the value of extension `Extensions_nyct_feed_header`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearNyctFeedHeader() {
    clearExtensionValue(ext: Extensions_nyct_feed_header)
  }
}

extension TransitRealtime_TripDescriptor {

  public var nyctTripDescriptor: NyctTripDescriptor {
    get {return getExtensionValue(ext: Extensions_nyct_trip_descriptor) ?? NyctTripDescriptor()}
    set {setExtensionValue(ext: Extensions_nyct_trip_descriptor, value: newValue)}
  }
  /// Returns true if extension `Extensions_nyct_trip_descriptor`
  /// has been explicitly set.
  public var hasNyctTripDescriptor: Bool {
    return hasExtensionValue(ext: Extensions_nyct_trip_descriptor)
  }
  /// Clears the value of extension `Extensions_nyct_trip_descriptor`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearNyctTripDescriptor() {
    clearExtensionValue(ext: Extensions_nyct_trip_descriptor)
  }
}

extension TransitRealtime_TripUpdate.StopTimeUpdate {

  public var nyctStopTimeUpdate: NyctStopTimeUpdate {
    get {return getExtensionValue(ext: Extensions_nyct_stop_time_update) ?? NyctStopTimeUpdate()}
    set {setExtensionValue(ext: Extensions_nyct_stop_time_update, value: newValue)}
  }
  /// Returns true if extension `Extensions_nyct_stop_time_update`
  /// has been explicitly set.
  public var hasNyctStopTimeUpdate: Bool {
    return hasExtensionValue(ext: Extensions_nyct_stop_time_update)
  }
  /// Clears the value of extension `Extensions_nyct_stop_time_update`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearNyctStopTimeUpdate() {
    clearExtensionValue(ext: Extensions_nyct_stop_time_update)
  }

}

// MARK: - File's ExtensionMap: Nyct_u45Subway_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let Nyct_u45Subway_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Extensions_nyct_feed_header,
  Extensions_nyct_trip_descriptor,
  Extensions_nyct_stop_time_update
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public let Extensions_nyct_feed_header = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<NyctFeedHeader>, TransitRealtime_FeedHeader>(
  _protobuf_fieldNumber: 1001,
  fieldName: "nyct_feed_header"
)

public let Extensions_nyct_trip_descriptor = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<NyctTripDescriptor>, TransitRealtime_TripDescriptor>(
  _protobuf_fieldNumber: 1001,
  fieldName: "nyct_trip_descriptor"
)

public let Extensions_nyct_stop_time_update = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<NyctStopTimeUpdate>, TransitRealtime_TripUpdate.StopTimeUpdate>(
  _protobuf_fieldNumber: 1001,
  fieldName: "nyct_stop_time_update"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension NyctFeedHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "NyctFeedHeader"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}nyct_subway_version\0\u{3}trip_replacement_period\0")

  public var isInitialized: Bool {
    if self._nyctSubwayVersion == nil {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.tripReplacementPeriod) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._nyctSubwayVersion) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.tripReplacementPeriod) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nyctSubwayVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    if !self.tripReplacementPeriod.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tripReplacementPeriod, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NyctFeedHeader, rhs: NyctFeedHeader) -> Bool {
    if lhs._nyctSubwayVersion != rhs._nyctSubwayVersion {return false}
    if lhs.tripReplacementPeriod != rhs.tripReplacementPeriod {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension NyctFeedHeader.TripReplacementPeriod_ReplacementPeriod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN\0")
}

extension NyctTripReplacementPeriod: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "NyctTripReplacementPeriod"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}route_id\0\u{3}replacement_period\0")

  public var isInitialized: Bool {
    if let v = self._replacementPeriod, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._routeID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._replacementPeriod) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._routeID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._replacementPeriod {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NyctTripReplacementPeriod, rhs: NyctTripReplacementPeriod) -> Bool {
    if lhs._routeID != rhs._routeID {return false}
    if lhs._replacementPeriod != rhs._replacementPeriod {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension NyctTripDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "NyctTripDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}train_id\0\u{3}is_assigned\0\u{1}direction\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._trainID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._isAssigned) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._direction) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._trainID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._isAssigned {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._direction {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NyctTripDescriptor, rhs: NyctTripDescriptor) -> Bool {
    if lhs._trainID != rhs._trainID {return false}
    if lhs._isAssigned != rhs._isAssigned {return false}
    if lhs._direction != rhs._direction {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension NyctTripDescriptor.Direction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}NORTH\0\u{1}EAST\0\u{1}SOUTH\0\u{1}WEST\0")
}

extension NyctStopTimeUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "NyctStopTimeUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}scheduled_track\0\u{3}actual_track\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._scheduledTrack) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._actualTrack) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._scheduledTrack {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._actualTrack {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NyctStopTimeUpdate, rhs: NyctStopTimeUpdate) -> Bool {
    if lhs._scheduledTrack != rhs._scheduledTrack {return false}
    if lhs._actualTrack != rhs._actualTrack {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
